
volumes:
  mongo-db-vol:

services:
    
  mongo:
    image: mongo:4.4.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-db-vol:/data/db

  mongo-test:
    image: mongo:4.4.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017